### ISSUE TITLE
Only reporting A value from Iclicker

### ISSUE THREAD

**Issue by aziddy** [wizard97/iSkipper#4]
Using a Adafruit feather 32u4 with rfm69HCW

Using the iskipper program example with the IRQ and CNS set for the board .

Only shows A values with wrong clicker ID's from iclickers.
B,C,D and E values dont show up.

Any idea why?

**Comment by wizard97** [comment]
Hmm,

That is very weird. Might have to do with incorrect handling with the HW version, this has only been tested on the W version. Also really make sure your interrupt pins are correct.

Also, do you by any chance have a different RFM69 library installed? 

Could you perhaps try one of the other examples and let me know? I added some more examples, please clone again and reinstall everything, then try capture.

Update: I just tested the basic iSkipper program and it is working fine for me with a Teensy3.2. I'm suspecting the issue is much more subtle. What remote type are you using?

**Comment by wizard97** [comment]
I just checked the pinout for the Feather.

Can you confirm you set
IRQ to 7
and CSN to 8?

**Comment by aziddy** [comment]
Iclicker one. Just tried your updated program on it at and it still gives the same wrong results

Only A values from the wrong clicker ID for example it gives B4, D1, B9, DC for 14D0B97D clicker

This feather is probably a defect because I tried this on another feather 32u4 with rfm69HCW before and it works fine with the same IDE version, Libraries and program with the correct pin out .
